name: CI Pipeline

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker images
        run: docker compose build

      - name: Tag backend image
        run: docker tag tours-backend ghcr.io/${{ github.repository }}/backend:latest

      - name: Tag frontend image
        run: docker tag tours-frontend ghcr.io/${{ github.repository }}/frontend:latest

      - name: Push backend image
        run: docker push ghcr.io/${{ github.repository }}/backend:latest

      - name: Push frontend image
        run: docker push ghcr.io/${{ github.repository }}/frontend:latest
