name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show folder structure (debug)
        run: ls -R

      - name: Install backend deps
        run: |
          cd tours-activity-platform/backend
          npm install

      - name: Run ESLint
        run: |
          cd tours-activity-platform/backend
          npx eslint .

      - name: Build Docker images
        run: docker compose -f tours-activity-platform/docker-compose.yml build
